-- ============================================================
-- Nexora DEV setup — run this once in Snowflake Worksheet
-- Context: DEV_NEXORA.ANALYTICS (+ DEV_NEXORA.RAW), warehouse DEV_NEXORA_WH
-- ============================================================

USE DATABASE DEV_NEXORA;
USE WAREHOUSE DEV_NEXORA_WH;

-- ── 1. Core scheduler write table — lives in RAW, not ANALYTICS ─
USE SCHEMA RAW;

CREATE TABLE IF NOT EXISTS STORE_MANUAL_LABOR_HOURS (
    EMPLOYEE_ID   VARCHAR(250)  NOT NULL DEFAULT '',
    LOCATION_ID   VARCHAR(250)  NOT NULL,
    WORK_DATE     DATE          NOT NULL,
    SHIFT_NO      NUMBER(38,0)  NOT NULL,
    DAY_NAME      VARCHAR(20),
    START_TIME    TIME          NOT NULL,
    END_TIME      TIME          NOT NULL,
    HOURS_WORKED  NUMBER(10,2),
    PAY_TYPE      VARCHAR(20)   DEFAULT 'HOURLY',
    CREATED_AT    TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_USER  VARCHAR(250)  DEFAULT CURRENT_USER(),
    UPDATED_AT    TIMESTAMP_NTZ,
    UPDATED_USER  VARCHAR(250),
    CONSTRAINT PK_STORE_MANUAL_LABOR_HOURS
        PRIMARY KEY (LOCATION_ID, WORK_DATE, SHIFT_NO, EMPLOYEE_ID)
);

-- ── 2. Weekly labor cost rollup (powers Reports KPIs) ───────
USE SCHEMA ANALYTICS;

CREATE TABLE IF NOT EXISTS STORE_MANUAL_LABOR_WEEKLY_SUMMARY (
    LOCATION_ID          VARCHAR(250)  NOT NULL,
    EMPLOYEE_ID          VARCHAR(250)  NOT NULL,
    WEEK_START_DT        DATE          NOT NULL,
    REG_HOURS            NUMBER(10,2)  DEFAULT 0,
    OT_HOURS             NUMBER(10,2)  DEFAULT 0,
    REG_COST             NUMBER(15,2)  DEFAULT 0,
    OT_COST              NUMBER(15,2)  DEFAULT 0,
    TOTAL_HOURS          NUMBER(10,2)  DEFAULT 0,
    TOTAL_COST           NUMBER(15,2)  DEFAULT 0,
    PAY_TYPE             VARCHAR(20)   DEFAULT 'HOURLY',
    IS_MANUAL_OVERRIDE   BOOLEAN       DEFAULT FALSE,
    MANUAL_WEEKLY_SALARY NUMBER(15,2),
    CREATED_AT           TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT           TIMESTAMP_NTZ,
    CONSTRAINT PK_STORE_MANUAL_LABOR_WEEKLY_SUMMARY
        PRIMARY KEY (LOCATION_ID, EMPLOYEE_ID, WEEK_START_DT)
);

-- ── 3. Manual expense entries (Reports page) ─────────────────
CREATE TABLE IF NOT EXISTS STORE_MANUAL_EXPENSES (
    LOCATION_ID      VARCHAR(250)  NOT NULL,
    EXPENSE_TYPE     VARCHAR(100)  NOT NULL,
    EXPENSE_MONTH    DATE          NOT NULL,
    EXPENSE_AMT      NUMBER(15,2)  NOT NULL,
    EXPENSE_DT       DATE          DEFAULT CURRENT_DATE(),
    EXPENSE_COMMENTS VARCHAR(500),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_USER     VARCHAR(250)  DEFAULT CURRENT_USER()
);

-- ── 4. App authentication table ──────────────────────────────
CREATE TABLE IF NOT EXISTS APP_USER_ACCOUNTS (
    USERNAME           VARCHAR(250)  NOT NULL,
    LOCATION_ID        VARCHAR(250)  NOT NULL,
    PASSWORD_HASH      VARCHAR(500)  NOT NULL,
    USER_ROLE          VARCHAR(50)   DEFAULT 'MANAGER',
    IS_ACTIVE          BOOLEAN       DEFAULT TRUE,
    LAST_LOGIN_AT      TIMESTAMP_NTZ,
    FAILED_LOGIN_COUNT NUMBER(5,0)   DEFAULT 0,
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_APP_USER_ACCOUNTS PRIMARY KEY (USERNAME, LOCATION_ID)
);

-- Seed: one test login per store (password stored plain for dev — replace with bcrypt hash in prod)
-- Stores: SS-212, SS-223, SS-225B, SS-227B, SS-232B, SS-235B, SS-300B, SS-401B, SS-600B, SS-601
INSERT INTO APP_USER_ACCOUNTS (USERNAME, LOCATION_ID, PASSWORD_HASH, USER_ROLE) VALUES
    ('admin', 'SS-212',  'admin123', 'ADMIN'),
    ('admin', 'SS-223',  'admin123', 'ADMIN'),
    ('admin', 'SS-225B', 'admin123', 'ADMIN'),
    ('admin', 'SS-227B', 'admin123', 'ADMIN'),
    ('admin', 'SS-232B', 'admin123', 'ADMIN'),
    ('admin', 'SS-235B', 'admin123', 'ADMIN'),
    ('admin', 'SS-300B', 'admin123', 'ADMIN'),
    ('admin', 'SS-401B', 'admin123', 'ADMIN'),
    ('admin', 'SS-600B', 'admin123', 'ADMIN'),
    ('admin', 'SS-601',  'admin123', 'ADMIN');

-- ── 5. Time-off requests ─────────────────────────────────────
CREATE TABLE IF NOT EXISTS APP_TIME_OFF_REQUESTS (
    REQUEST_ID       VARCHAR(250)  NOT NULL,
    EMPLOYEE_ID      VARCHAR(250)  NOT NULL,
    LOCATION_ID      VARCHAR(250)  NOT NULL,
    REQUEST_TYPE     VARCHAR(50)   NOT NULL,
    START_DATE       DATE          NOT NULL,
    END_DATE         DATE          NOT NULL,
    REASON           VARCHAR(1000),
    STATUS           VARCHAR(50)   DEFAULT 'pending',
    SUBMITTED_AT     TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DECIDED_AT       TIMESTAMP_NTZ,
    DECIDED_BY       VARCHAR(250),
    MANAGER_COMMENT  VARCHAR(1000),
    CREATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CREATED_USER     VARCHAR(250)  DEFAULT CURRENT_USER(),
    UPDATED_USER     VARCHAR(250)  DEFAULT CURRENT_USER(),
    CONSTRAINT PK_APP_TIME_OFF_REQUESTS PRIMARY KEY (REQUEST_ID)
);

-- ── 6. Shift swaps ───────────────────────────────────────────
CREATE TABLE IF NOT EXISTS APP_SHIFT_SWAPS (
    SWAP_ID            VARCHAR(250)  NOT NULL,
    FROM_EMPLOYEE_ID   VARCHAR(250)  NOT NULL,
    TO_EMPLOYEE_ID     VARCHAR(250)  NOT NULL,
    FROM_LOCATION_ID   VARCHAR(250)  NOT NULL,
    FROM_WORK_DATE     DATE          NOT NULL,
    FROM_START_TIME    TIME          NOT NULL,
    FROM_SHIFT_NO      NUMBER(38,0)  NOT NULL,
    TO_WORK_DATE       DATE          NOT NULL,
    TO_START_TIME      TIME          NOT NULL,
    TO_SHIFT_NO        NUMBER(38,0)  NOT NULL,
    STATUS             VARCHAR(50)   DEFAULT 'pending',
    HAS_CONFLICT       BOOLEAN       DEFAULT FALSE,
    CONFLICT_REASONS   VARCHAR(1000),
    SUBMITTED_AT       TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    DECIDED_AT         TIMESTAMP_NTZ,
    DECIDED_BY         VARCHAR(250),
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    UPDATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    CONSTRAINT PK_APP_SHIFT_SWAPS PRIMARY KEY (SWAP_ID)
);

-- ── 7. In-app notifications ──────────────────────────────────
CREATE TABLE IF NOT EXISTS APP_NOTIFICATIONS (
    NOTIFICATION_ID    VARCHAR(250)  NOT NULL,
    RECIPIENT_USERNAME VARCHAR(250)  NOT NULL,
    LOCATION_ID        VARCHAR(250)  NOT NULL,
    NOTIFICATION_TYPE  VARCHAR(50)   NOT NULL,
    TITLE              VARCHAR(500)  NOT NULL,
    SUBTITLE           VARCHAR(1000),
    ACTOR_EMPLOYEE_ID  VARCHAR(250),
    IS_READ            BOOLEAN       DEFAULT FALSE,
    LINK               VARCHAR(500),
    CREATED_AT         TIMESTAMP_NTZ DEFAULT CURRENT_TIMESTAMP(),
    EXPIRES_AT         TIMESTAMP_NTZ,
    CONSTRAINT PK_APP_NOTIFICATIONS PRIMARY KEY (NOTIFICATION_ID)
);
